# Copyright (c) Borislav Stanimirov
# SPDX-License-Identifier: MIT
#
set(PACKAGE_VERSION @PROJECT_VERSION@)
if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE YES)
    set(PACKAGE_VERSION_EXACT YES)
endif()
