name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Install LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm
      - name: Configure
        run: cmake --preset=debug-coverage -B coverage
      - name: Build
        run: cmake --build coverage
      - name: Test
        run: ctest --test-dir coverage --output-on-failure
        env:
          LLVM_PROFILE_FILE: coverage.profraw
      - name: Generate Coverage Report
        run: |
          llvm-profdata merge -sparse coverage/test/coverage.profraw -o coverage.profdata
          llvm-cov export coverage/test/itlib* -instr-profile=coverage.profdata -format=lcov > coverage.lcov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
